import "server-only";
import type { MarketIntelligenceRepository } from "@/core/application/ports/market-intelligence-port";
import type { MarketIntelligenceProfile, MarketPattern, MarketReference } from "@/core/domain/entities/market-intelligence";
import type { GenesisClient } from "@/infrastructure/supabase/server-client";
import type { Json, MarketIntelligenceProfileRow, MarketIntelligenceReferenceRow, MarketIntelligencePatternRow } from "@/infrastructure/supabase/database.types";
import { translateError, unwrap } from "./errors";

const profile = (row: MarketIntelligenceProfileRow): MarketIntelligenceProfile => ({ organisationId: row.organisation_id, businessObjectives: row.business_objectives as MarketIntelligenceProfile["businessObjectives"], targetGeographies: row.target_geographies, serviceAreas: row.service_areas, audienceContext: row.audience_context, culturalContext: row.cultural_context, promotionalFocus: row.promotional_focus, culturalVoiceLevel: row.cultural_voice_level, conversionActions: row.conversion_actions, platformStrategy: row.platform_strategy as MarketIntelligenceProfile["platformStrategy"], hashtagStrategy: row.hashtag_strategy as MarketIntelligenceProfile["hashtagStrategy"], createdAt: row.created_at, updatedAt: row.updated_at });
const reference = (row: MarketIntelligenceReferenceRow): MarketReference => ({ id: row.id, organisationId: row.organisation_id, identifier: row.identifier, platform: row.platform, market: row.market, vertical: row.vertical, relevanceNote: row.relevance_note, sourceUrl: row.source_url, isActive: row.is_active, reviewedAt: row.reviewed_at, createdAt: row.created_at, updatedAt: row.updated_at });
const pattern = (row: MarketIntelligencePatternRow): MarketPattern => ({ id: row.id, organisationId: row.organisation_id, observation: row.observation, category: row.category, platform: row.platform, market: row.market, vertical: row.vertical, provenance: row.provenance, sourceUrl: row.source_url, confidence: row.confidence, observedAt: row.observed_at, reviewedAt: row.reviewed_at, isActive: row.is_active, createdAt: row.created_at, updatedAt: row.updated_at });

export class SupabaseMarketIntelligenceRepository implements MarketIntelligenceRepository {
  constructor(private readonly client: GenesisClient) {}
  async getProfile(organisationId: string) { const { data, error } = await this.client.from("market_intelligence_profiles").select("*").eq("organisation_id", organisationId).maybeSingle(); if (error) translateError(error, "Market Intelligence profile"); return data ? profile(data) : null; }
  async getSnapshot(organisationId: string) { const [p, refs, patterns] = await Promise.all([this.getProfile(organisationId), this.client.from("market_intelligence_references").select("*").eq("organisation_id", organisationId).order("identifier"), this.client.from("market_intelligence_patterns").select("*").eq("organisation_id", organisationId).order("created_at", { ascending: false })]); if (refs.error) translateError(refs.error, "Market Intelligence references"); if (patterns.error) translateError(patterns.error, "Market Intelligence patterns"); return { profile: p, references: (refs.data ?? []).map(reference), patterns: (patterns.data ?? []).map(pattern) }; }
  async upsertProfile(input: Omit<MarketIntelligenceProfile, "createdAt" | "updatedAt">) { const result = await this.client.from("market_intelligence_profiles").upsert({ organisation_id: input.organisationId, business_objectives: input.businessObjectives, target_geographies: input.targetGeographies, service_areas: input.serviceAreas, audience_context: input.audienceContext, cultural_context: input.culturalContext, promotional_focus: input.promotionalFocus, cultural_voice_level: input.culturalVoiceLevel, conversion_actions: input.conversionActions, platform_strategy: input.platformStrategy as Json, hashtag_strategy: input.hashtagStrategy as Json }, { onConflict: "organisation_id" }).select("*").single(); return profile(unwrap(result, "Market Intelligence profile")); }
  async createReference(input: Omit<MarketReference, "id" | "createdAt" | "updatedAt">) { const result = await this.client.from("market_intelligence_references").insert({ organisation_id: input.organisationId, identifier: input.identifier, platform: input.platform, market: input.market, vertical: input.vertical, relevance_note: input.relevanceNote, source_url: input.sourceUrl, is_active: input.isActive, reviewed_at: input.reviewedAt }).select("*").single(); return reference(unwrap(result, "Market Intelligence reference")); }
  async createPattern(input: Omit<MarketPattern, "id" | "createdAt" | "updatedAt">) { const result = await this.client.from("market_intelligence_patterns").insert({ organisation_id: input.organisationId, observation: input.observation, category: input.category, platform: input.platform, market: input.market, vertical: input.vertical, provenance: input.provenance, source_url: input.sourceUrl, confidence: input.confidence, observed_at: input.observedAt, reviewed_at: input.reviewedAt, is_active: input.isActive }).select("*").single(); return pattern(unwrap(result, "Market Intelligence pattern")); }
}
