import { notFound } from "next/navigation";
import { requireContext } from "@/server/container";
import { marketProfileReadiness, BUSINESS_OBJECTIVES, CULTURAL_VOICE_LEVELS, PATTERN_CATEGORIES } from "@/core/domain/entities/market-intelligence";
import { PageHeader } from "@/components/common/page-header";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { saveMarketProfileAction, addMarketReferenceAction, addMarketPatternAction } from "@/server/actions/market-intelligence";
import { getMembrainOverview } from "@/core/application/use-cases/membrain";
import { deriveGrowthReadinessFromGenesis, deriveMeasurementReadiness, emptyImpactCheckpoint } from "@/core/domain/entities/acor";
import { blotatoConfig } from "@/infrastructure/blotato/blotato-config";

const input = "w-full rounded-md border border-border bg-input px-3 py-2 text-sm";
export default async function MarketIntelligencePage({ params, searchParams }: { params: Promise<{ orgId: string }>; searchParams: Promise<{ saved?: string }> }) {
  const [{ orgId }, query] = await Promise.all([params, searchParams]); const context = await requireContext();
  const [organisation, snapshot, membrain, connectedAccounts, metricSnapshots] = await Promise.all([context.organisations.findById(orgId), context.marketIntelligence.getSnapshot(orgId), getMembrainOverview({ actor: context.actor, organisations: context.organisations, membrain: context.membrain }, orgId), context.blotatoAccounts.listActiveForOrganisation(orgId), context.engagement.listMetricSnapshotsForOrganisation?.(orgId) ?? Promise.resolve([])]);
  if (!organisation) notFound(); const readiness = marketProfileReadiness(snapshot.profile); const profile = snapshot.profile;
  const signal = (key: string) => membrain.readiness.signals.find(item => item.categoryKey === key)?.met ?? false;
  const measurement = deriveMeasurementReadiness({ blotatoEnabled: blotatoConfig().enabled, connectedProviderAccountCount: connectedAccounts.length, snapshots: metricSnapshots });
  const growthReadiness = deriveGrowthReadinessFromGenesis({ brandDescriptionReady: signal("brand_description"), brandVoiceReady: signal("brand_voice"), membrainReady: membrain.readiness.percentage === 100, marketIntelligenceReady: readiness.percentage === 100, conversionActions: profile?.conversionActions ?? [], approvedPriorityProof: snapshot.patterns.some(pattern => pattern.category === "proof" && pattern.isActive && Boolean(pattern.reviewedAt) && pattern.confidence >= 70), baselineCaptured: snapshot.references.some(reference => reference.isActive && /day-0/i.test(reference.identifier)), connectedPlatformCount: connectedAccounts.length, measurementConfigured: measurement.configured, measurementDataExists: measurement.dataExists, adaptiveEvidenceReady: measurement.adaptiveEvidenceReady });
  const impact = ([30, 60, 90] as const).map(emptyImpactCheckpoint);
  return <div className="flex max-w-4xl flex-col gap-6">
    <PageHeader eyebrow="Awo" title="Market Intelligence" description="Client-owned strategy and approved market patterns. MemBrain remains authoritative for brand facts, offers, services and contact channels." />
    <Card><CardHeader><CardTitle>ACOR Growth Readiness · {growthReadiness.lifecycle.replaceAll("_", " ")}</CardTitle><CardDescription>{growthReadiness.metCount} of {growthReadiness.total} explicit gates complete. This is not the forensic review score.</CardDescription></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2">{growthReadiness.gates.map(gate=><div className="rounded-md border border-border p-3 text-sm" key={gate.key}><strong>{gate.met ? "Ready" : "Gap"} · {gate.label}</strong><p className="mt-1 text-xs text-muted-foreground">{gate.evidence}</p></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>30 / 60 / 90 impact framework</CardTitle><CardDescription>Visibility, engagement, intent and explicit commercial outcomes remain separate. Empty values mean not measured.</CardDescription></CardHeader><CardContent className="grid gap-2 sm:grid-cols-3">{impact.map(point=><div className="rounded-md border border-border p-3 text-sm" key={point.day}><strong>Day {point.day}</strong><p className="mt-1 text-xs text-muted-foreground">Visibility · Engagement · Intent · Commercial outcomes</p></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Profile readiness · {readiness.percentage}%</CardTitle><CardDescription>{readiness.complete} of {readiness.total} deterministic profile areas configured.</CardDescription></CardHeader><CardContent>
      {query.saved === "1" ? <div className="mb-4 rounded-md border border-positive/40 bg-positive-soft px-3 py-2 text-sm text-positive" role="status"><strong>Profile saved.</strong> The readiness score above reflects the stored values.</div> : null}
      <form action={saveMarketProfileAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="organisationId" value={orgId}/>
        <label className="text-sm">Business objectives<input className={input} name="businessObjectives" defaultValue={profile?.businessObjectives.join(", ")} placeholder={BUSINESS_OBJECTIVES.join(", ")}/></label>
        <label className="text-sm">Cultural voice<select className={input} name="culturalVoiceLevel" defaultValue={profile?.culturalVoiceLevel ?? "neutral"}>{CULTURAL_VOICE_LEVELS.map(v=><option key={v} value={v}>{v.replaceAll("_", " ").toUpperCase()}</option>)}</select></label>
        <label className="text-sm">Target geography<input className={input} name="targetGeographies" defaultValue={profile?.targetGeographies.join(", ")}/></label>
        <label className="text-sm">Service area<input className={input} name="serviceAreas" defaultValue={profile?.serviceAreas.join(", ")}/></label>
        <label className="text-sm sm:col-span-2">Audience context<textarea className={input} name="audienceContext" defaultValue={profile?.audienceContext ?? ""}/></label>
        <label className="text-sm sm:col-span-2">Cultural context<textarea className={input} name="culturalContext" defaultValue={profile?.culturalContext ?? ""}/></label>
        <label className="text-sm">Promotional focus<input className={input} name="promotionalFocus" defaultValue={profile?.promotionalFocus ?? ""}/></label>
        <label className="text-sm">Conversion action types<input className={input} name="conversionActions" defaultValue={profile?.conversionActions.join(", ")} placeholder="DM, enquiry, consultation"/></label>
        {(["instagram","facebook","linkedin","x","tiktok"] as const).map(platform=><label className="text-sm" key={platform}>{platform} strategy<input className={input} name={`${platform}PlatformStrategy`} defaultValue={profile?.platformStrategy[platform] ?? ""}/></label>)}
        {(["local","service","audience","occasion","campaign","brand"] as const).map(role=><label className="text-sm" key={role}>{role} discovery strategy<input className={input} name={`${role}Strategy`} defaultValue={profile?.hashtagStrategy[role === "audience" ? "audience_cultural" : role === "occasion" ? "occasion_topic" : role] ?? ""}/></label>)}
        <button className="w-fit rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Save profile</button>
      </form></CardContent></Card>
    <Card><CardHeader><CardTitle>Reference set</CardTitle><CardDescription>Identifiers and relevance only. No scraped caption archive.</CardDescription></CardHeader><CardContent className="space-y-4"><ul className="space-y-2 text-sm">{snapshot.references.map(r=><li key={r.id}><strong>{r.identifier}</strong> · {r.platform} · {r.relevanceNote}</li>)}</ul><form action={addMarketReferenceAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="organisationId" value={orgId}/><input className={input} name="identifier" required placeholder="Account or brand identifier"/><input className={input} name="platform" required placeholder="Platform"/><input className={input} name="market" placeholder="Market"/><input className={input} name="vertical" placeholder="Vertical"/><input className={input} name="sourceUrl" type="url" placeholder="Source URL"/><input className={input} name="relevanceNote" required placeholder="Why this reference is relevant"/><button className="w-fit rounded-md border border-border px-3 py-2 text-sm">Add reference</button></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Approved market patterns</CardTitle><CardDescription>Human-approved abstractions. Awo never imitates named accounts or stores competitor captions.</CardDescription></CardHeader><CardContent className="space-y-4"><ul className="space-y-2 text-sm">{snapshot.patterns.map(p=><li key={p.id}><strong>{p.category.replaceAll("_", " ")}</strong> · {p.observation} <span className="text-muted-foreground">({p.confidence}% confidence)</span></li>)}</ul><form action={addMarketPatternAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="organisationId" value={orgId}/><select className={input} name="category">{PATTERN_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><input className={input} name="platform" placeholder="Platform (optional)"/><textarea className={`${input} sm:col-span-2`} name="observation" minLength={20} maxLength={1000} required placeholder="Abstract, original market observation"/><input className={input} name="provenance" required placeholder="Provenance / research note"/><input className={input} name="sourceUrl" type="url" placeholder="Source URL"/><input className={input} name="market" placeholder="Market"/><input className={input} name="vertical" placeholder="Vertical"/><input className={input} name="confidence" type="number" min="0" max="100" defaultValue="50"/><button className="w-fit rounded-md border border-border px-3 py-2 text-sm">Add approved pattern</button></form></CardContent></Card>
  </div>;
}
