import type { CheckResult, ReliabilityReport } from "./types";

const STATUS_LABEL: Record<CheckResult["status"], string> = { PASS: "PASS", FAIL: "FAIL", SKIP: "SKIP" };

export function renderConsoleReport(report: ReliabilityReport): string {
  const lines: string[] = [];
  lines.push("VILLIZ SOCIAL MANAGER");
  lines.push("PUBLISHING RELIABILITY REPORT");
  lines.push("");
  lines.push(`Environment: ${report.environment}`);
  lines.push(`Run ID:      ${report.runId}`);
  lines.push(`Git commit:  ${report.gitCommit}`);
  lines.push(`Started:     ${report.timestamp}`);
  lines.push(`Duration:    ${report.durationMs}ms`);
  lines.push("");

  for (const result of report.results) {
    const tag = `[${STATUS_LABEL[result.status]}]`.padEnd(6);
    const classification = `(${result.classification})`.padEnd(12);
    const duration = `${result.durationMs}ms`.padStart(7);
    lines.push(`${tag} ${classification} ${result.name} — ${duration}`);
    if (result.status !== "PASS" && result.message) {
      lines.push(`         ${result.message}`);
    }
  }

  lines.push("");
  lines.push(`Core Reliability Score: ${report.coreReliabilityScore === null ? "n/a (no mandatory checks ran)" : `${report.coreReliabilityScore}%`}`);
  lines.push(`Mandatory checks passed: ${countMandatoryPassed(report)}/${countMandatoryRan(report)}`);
  lines.push(`External dependency status: ${report.externalDependencyStatus}`);
  lines.push(`Skipped checks: ${report.skippedChecks}`);
  lines.push(`Result: ${report.releaseRecommendation}`);

  if (report.knownLimitations.length > 0) {
    lines.push("");
    lines.push("Known limitations:");
    for (const limitation of report.knownLimitations) lines.push(`  - ${limitation}`);
  }

  return lines.join("\n");
}

function countMandatoryRan(report: ReliabilityReport): number {
  return report.results.filter((r) => r.classification === "MANDATORY" && r.status !== "SKIP").length;
}

function countMandatoryPassed(report: ReliabilityReport): number {
  return report.results.filter((r) => r.classification === "MANDATORY" && r.status === "PASS").length;
}

export function renderMarkdownReport(report: ReliabilityReport): string {
  const lines: string[] = [];
  lines.push("# Villiz Social Manager — Publishing Reliability Report");
  lines.push("");
  lines.push(`**Run ID:** \`${report.runId}\`  `);
  lines.push(`**When:** ${report.timestamp}  `);
  lines.push(`**Commit:** \`${report.gitCommit}\`  `);
  lines.push(`**Environment:** ${report.environment}  `);
  lines.push(`**Duration:** ${report.durationMs}ms`);
  lines.push("");
  lines.push(`## Result: ${report.releaseRecommendation}`);
  lines.push("");
  lines.push(
    report.releaseRecommendation === "READY"
      ? "All mandatory checks passed. It is safe to proceed with this release from a publishing-reliability standpoint."
      : report.releaseRecommendation === "READY WITH WARNINGS"
        ? "All mandatory checks passed, but at least one advisory check failed or a mandatory check was skipped because its environment (e.g. local Supabase) wasn't available. Review the warnings below before releasing."
        : "At least one mandatory check failed. Do not release until this is resolved.",
  );
  lines.push("");
  lines.push(`- **Core Reliability Score:** ${report.coreReliabilityScore === null ? "n/a" : `${report.coreReliabilityScore}%`}`);
  lines.push(`- **Mandatory checks:** ${report.passedChecks}/${report.totalChecks - report.skippedChecks} passed (excluding skipped)`);
  lines.push(`- **External dependency status:** ${report.externalDependencyStatus}`);
  lines.push("");
  lines.push("## Checks");
  lines.push("");
  lines.push("| Status | Classification | Check | Duration |");
  lines.push("|---|---|---|---|");
  for (const result of report.results) {
    lines.push(`| ${STATUS_LABEL[result.status]} | ${result.classification} | ${result.name} | ${result.durationMs}ms |`);
  }

  const failures = report.results.filter((r) => r.status === "FAIL");
  if (failures.length > 0) {
    lines.push("");
    lines.push("## Failures");
    lines.push("");
    for (const failure of failures) {
      lines.push(`### ${failure.name}`);
      lines.push("");
      lines.push(failure.message ?? "(no message)");
      lines.push("");
    }
  }

  const skips = report.results.filter((r) => r.status === "SKIP");
  if (skips.length > 0) {
    lines.push("## Skipped");
    lines.push("");
    for (const skip of skips) {
      lines.push(`- **${skip.name}**: ${skip.message ?? "no reason given"}`);
    }
    lines.push("");
  }

  if (report.knownLimitations.length > 0) {
    lines.push("## Known limitations");
    lines.push("");
    for (const limitation of report.knownLimitations) lines.push(`- ${limitation}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by `npm run reliability:test` — see docs/RELIABILITY_TESTING.md._");

  return lines.join("\n");
}
